# Form implementation generated from reading ui file 'helpform.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_helpform(object):
    def setupUi(self, helpform):
        helpform.setObjectName("helpform")
        helpform.resize(1119, 520)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        helpform.setFont(font)
        self.help_browser = QtWidgets.QTextBrowser(parent=helpform)
        self.help_browser.setGeometry(QtCore.QRect(0, 0, 1119, 520))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 170))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.help_browser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        self.help_browser.setFont(font)
        self.help_browser.setStyleSheet("background-color: rgba(255, 255, 255, 0)")
        self.help_browser.setObjectName("help_browser")
        self.back_label = QtWidgets.QLabel(parent=helpform)
        self.back_label.setGeometry(QtCore.QRect(0, 0, 1119, 520))
        self.back_label.setStyleSheet("border-image: url(:/image/image/xiaomeng.jpg);")
        self.back_label.setText("")
        self.back_label.setObjectName("back_label")
        self.back_label2 = QtWidgets.QLabel(parent=helpform)
        self.back_label2.setGeometry(QtCore.QRect(0, 0, 1119, 520))
        self.back_label2.setStyleSheet("background-color: rgba(255, 255, 255, 130);")
        self.back_label2.setText("")
        self.back_label2.setObjectName("back_label2")
        self.back_label.raise_()
        self.back_label2.raise_()
        self.help_browser.raise_()

        self.retranslateUi(helpform)
        QtCore.QMetaObject.connectSlotsByName(helpform)

    def retranslateUi(self, helpform):
        _translate = QtCore.QCoreApplication.translate
        helpform.setWindowTitle(_translate("helpform", "Form"))
