# Form implementation generated from reading ui file 'infoform.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_infoform(object):
    def setupUi(self, infoform):
        infoform.setObjectName("infoform")
        infoform.resize(370, 600)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        infoform.setFont(font)
        self.tip_label = QtWidgets.QLabel(parent=infoform)
        self.tip_label.setGeometry(QtCore.QRect(20, 20, 331, 81))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(13)
        font.setBold(True)
        self.tip_label.setFont(font)
        self.tip_label.setWordWrap(True)
        self.tip_label.setObjectName("tip_label")
        self.back_label = QtWidgets.QLabel(parent=infoform)
        self.back_label.setGeometry(QtCore.QRect(0, 0, 370, 600))
        self.back_label.setStyleSheet("border-image: url(:/image/image/xiaomeng_V.jpg);")
        self.back_label.setText("")
        self.back_label.setObjectName("back_label")
        self.back_label2 = QtWidgets.QLabel(parent=infoform)
        self.back_label2.setGeometry(QtCore.QRect(0, 0, 370, 600))
        self.back_label2.setStyleSheet("background-color: rgba(255, 255, 255, 130);")
        self.back_label2.setText("")
        self.back_label2.setObjectName("back_label2")
        self.info_browser = QtWidgets.QTextBrowser(parent=infoform)
        self.info_browser.setGeometry(QtCore.QRect(20, 100, 331, 441))
        self.info_browser.setObjectName("info_browser")
        self.OK_button = QtWidgets.QPushButton(parent=infoform)
        self.OK_button.setGeometry(QtCore.QRect(110, 550, 131, 41))
        self.OK_button.setObjectName("OK_button")
        self.back_label.raise_()
        self.back_label2.raise_()
        self.tip_label.raise_()
        self.info_browser.raise_()
        self.OK_button.raise_()

        self.retranslateUi(infoform)
        QtCore.QMetaObject.connectSlotsByName(infoform)

    def retranslateUi(self, infoform):
        _translate = QtCore.QCoreApplication.translate
        infoform.setWindowTitle(_translate("infoform", "夜雨为伴-信息"))
        self.tip_label.setText(_translate("infoform", "提示文本  tip_label"))
        self.OK_button.setText(_translate("infoform", "关 闭"))
