# Form implementation generated from reading ui file 'supportform.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_supportform(object):
    def setupUi(self, supportform):
        supportform.setObjectName("supportform")
        supportform.resize(370, 600)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(14)
        supportform.setFont(font)
        self.tips_label2 = QtWidgets.QLabel(parent=supportform)
        self.tips_label2.setGeometry(QtCore.QRect(20, 480, 321, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        self.tips_label2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        font.setBold(True)
        self.tips_label2.setFont(font)
        self.tips_label2.setWordWrap(True)
        self.tips_label2.setObjectName("tips_label2")
        self.tips_label1 = QtWidgets.QLabel(parent=supportform)
        self.tips_label1.setGeometry(QtCore.QRect(20, 20, 331, 121))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(13)
        font.setBold(True)
        self.tips_label1.setFont(font)
        self.tips_label1.setWordWrap(True)
        self.tips_label1.setObjectName("tips_label1")
        self.image_label = QtWidgets.QLabel(parent=supportform)
        self.image_label.setGeometry(QtCore.QRect(20, 150, 320, 320))
        self.image_label.setStyleSheet("border-image: url(:/image/image/supportQR.jpg);")
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.back_label = QtWidgets.QLabel(parent=supportform)
        self.back_label.setGeometry(QtCore.QRect(0, 0, 370, 600))
        self.back_label.setStyleSheet("border-image: url(:/image/image/xiaomeng_V.jpg);")
        self.back_label.setText("")
        self.back_label.setObjectName("back_label")
        self.back_label2 = QtWidgets.QLabel(parent=supportform)
        self.back_label2.setGeometry(QtCore.QRect(0, 0, 370, 600))
        self.back_label2.setStyleSheet("background-color: rgba(255, 255, 255, 130);")
        self.back_label2.setText("")
        self.back_label2.setObjectName("back_label2")
        self.back_label.raise_()
        self.back_label2.raise_()
        self.tips_label2.raise_()
        self.tips_label1.raise_()
        self.image_label.raise_()

        self.retranslateUi(supportform)
        QtCore.QMetaObject.connectSlotsByName(supportform)

    def retranslateUi(self, supportform):
        _translate = QtCore.QCoreApplication.translate
        supportform.setWindowTitle(_translate("supportform", "夜雨为伴-赞助"))
        self.tips_label2.setText(_translate("supportform", "提示：安全当先，谨防诈骗，完全自愿，该二维码使用V信扫描，会跳转到支付窗口。\n"
"若您扫描后不是**柯，则程序已被修改，立马关闭。\n"
"如果您手滑了，请联系我，退给您。"))
        self.tips_label1.setText(_translate("supportform", "《道德经》曰：千里之行，始于足下。\n"
"\n"
"我曰：潺潺流水映初晖，感恩相伴赏时辉。\n"
"\n"
"制作不易，承蒙君不弃，够一瓶阔落便好。"))
